# Generated by Django 2.1.5 on 2019-07-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sweater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productcode', models.TextField(blank=True, null=True)),
                ('soldby', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pattern', models.TextField(blank=True, null=True)),
                ('neck', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('occasion', models.TextField(blank=True, null=True)),
                ('washcare', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
