# Generated by Django 2.1.5 on 2019-07-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandiCraft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweater',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
