# Generated by Django 2.1.5 on 2019-07-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandiCraft', '0002_sweater_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('productcode', models.TextField(blank=True, null=True)),
                ('soldby', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('shape', models.TextField(blank=True, null=True)),
                ('basemetal', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('occasion', models.TextField(blank=True, null=True)),
                ('closure', models.TextField(blank=True, null=True)),
                ('multipackset', models.TextField(blank=True, null=True)),
                ('cost', models.TextField(blank=True, null=True)),
                ('person', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scarf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('productcode', models.TextField(blank=True, null=True)),
                ('soldby', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pattern', models.TextField(blank=True, null=True)),
                ('fabric', models.TextField(blank=True, null=True)),
                ('border', models.TextField(blank=True, null=True)),
                ('lengthandwidth', models.TextField(blank=True, null=True)),
                ('washcare', models.TextField(blank=True, null=True)),
                ('cost', models.TextField(blank=True, null=True)),
                ('person', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('productcode', models.TextField(blank=True, null=True)),
                ('soldby', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('length', models.TextField(blank=True, null=True)),
                ('multipackset', models.TextField(blank=True, null=True)),
                ('fabric', models.TextField(blank=True, null=True)),
                ('pattern', models.TextField(blank=True, null=True)),
                ('washcare', models.TextField(blank=True, null=True)),
                ('cost', models.TextField(blank=True, null=True)),
                ('person', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('productcode', models.TextField(blank=True, null=True)),
                ('soldby', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pattern', models.TextField(blank=True, null=True)),
                ('shape', models.TextField(blank=True, null=True)),
                ('material', models.TextField(blank=True, null=True)),
                ('colour', models.TextField(blank=True, null=True)),
                ('care', models.TextField(blank=True, null=True)),
                ('dimensions', models.TextField(blank=True, null=True)),
                ('cost', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sweater',
            name='cost',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sweater',
            name='person',
            field=models.TextField(blank=True, null=True),
        ),
    ]
