# Generated by Django 2.1.5 on 2019-07-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandiCraft', '0003_auto_20190729_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='earring',
            name='sizeandfit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
