# Generated by Django 2.1.5 on 2019-07-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HandiCraft', '0004_earring_sizeandfit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vase',
            name='care',
        ),
    ]
